repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: check-schema-modification
        name: Check firework cli schema modification
        entry: bash scripts/pre-commit/schema-update.sh
        language: system
        files: ^src/firework/cli/config/__init__.py$
